my_project/myapp/accounts/urls.py
from django.urls import path
from . import views
app_name = 'accounts'

urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
]

my_project/myapp/bbs/urls.py
from django.urls import path
from . import views
from .models import Article
from django.views import generic

app_name = 'bbs'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/update/', views.UpdateView.as_view(), name='update'),
    path('<int:id>/delete/', views.delete, name='delete'),
    path('create/', views.CreateView.as_view(), name='create'),
]

my_project/myapp/myapp/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView

urlpatterns = [
    path('', RedirectView.as_view(url='/bbs/')),
    path('index.html', RedirectView.as_view(url='/bbs/')),
    path('bbs/', include('bbs.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
]

my_project/myapp/accounts/models.py
from django.db import models

# Create your models here.

my_project/myapp/bbs/models.py
from django.db import models
from django.urls import reverse

class Article(models.Model):
    title = models.CharField(max_length = 200)
    content = models.TextField(max_length=1000)

    author = models.ForeignKey(
        'auth.User',
        on_delete = models.CASCADE,
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.content

    def get_absolute_url(self):
        return reverse('bbs:detail', kwargs={'pk': self.pk})

my_project/myapp/accounts/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic

class SignUpView(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'accounts/signup.html'

my_project/myapp/bbs/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Article
from django.views import generic
from django.db.models import Q
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied

class IndexView(generic.ListView):
    # model = Article
    def get_queryset(self):
        q_word = self.request.GET.get('query')
 
        # チェックボックスにチェックが入っている項目だけを検索対象とする
        selected_title = self.request.GET.get('title')
        selected_article = self.request.GET.get('article')
 
        if q_word:
            if selected_title and selected_article:
                object_list = Article.objects.filter(
                    Q(title__icontains=q_word) | Q(content__icontains=q_word))
            elif selected_title:
                object_list = Article.objects.filter(Q(title__icontains=q_word))
            else: # 投稿内容のみ、または両方ともチェックされていない場合は投稿内容のみを検索する
                object_list = Article.objects.filter(Q(content__icontains=q_word))
        else:
            object_list = Article.objects.all()
 
        return object_list
     
class DetailView(generic.DetailView):
    model = Article

class CreateView(LoginRequiredMixin, generic.edit.CreateView):
    model = Article
    fields = ['content', 'title', ]
 
    def form_valid(self, form):
        form.instance.author = self.request.user
        return super(CreateView, self).form_valid(form)

class UpdateView(generic.UpdateView):
    model = Article
    fields = ['content', 'title', ]
    def form_valid(self, form):
        form.instance.author = self.request.user
        return super(UpdateView, self).form_valid(form)

def delete(request, id):
    return HttpResponse('delete ' + str(id))

my_project/myapp/accounts/templates/accounts/signup.html
{% extends 'layout.html' %}

{% block content %}
<h1>ユーザー登録</h1>
<section class='common-form'>
    <form method='post'>
        {% csrf_token %}
        {{ form.as_p }}
        <button type='submit'>登録</button>
    </form>
</section>
{% endblock %}

my_project/myapp/bbs/templates/bbs/article_detail.html
{% extends 'layout.html' %}

{% block content %}

<h1 class="mt-3 mb-4">{{ article.title }}</h1>
<div>
    <p>{{ article.content }}</p>
    <p>{{ article.title }}</p>
    <p>{{ article.author }}</p>
    <p>{{ article.created_at|date:"Y-m-j H:i:s" }}<br>
    {{ article.updated_at|date:"Y-m-j H:i:s" }}</p>
</div>
<div class='mt-4'>
    <a href='{% url "bbs:update" article.pk %}'  class='btn btn-outline-primary mr-2'>編集</a>
    <a href='{% url "bbs:index" %}' class='btn btn-outline-primary'>一覧に戻る</a>
    <a href='{% url "bbs:delete" article.pk %}'  class='btn btn-danger ml-5'>削除</a>
</div>
{% endblock %}

my_project/myapp/bbs/templates/bbs/article_form.html
{% extends 'layout.html' %}

{% block content %}

<h1 class="mt-3 mb-4">{{ object|yesno:'投稿内容の更新,新規投稿の作成'}}</h1>

<form action='' method='post'>
    {% csrf_token %}
    <p>タイトル：{{ form.title }}</p>
    <p>本文：<br>
    {{ form.content }}</p>
    <button type='submit' class='submit btn btn-outline-primary'>{{ object|yesno:'更新,作成'}}</button>
</form>
<div class="mt-3">
    <a href='JavaScript:history.back()' class='btn btn-outline-primary'>戻る</a>
</div>

{% endblock %}

my_project/myapp/bbs/templates/bbs/article_list.html
{% extends 'layout.html' %}

{% load markdown_extras %}

{% block content %}

    <h1 class="mt-3 mb-4">投稿一覧</h1>

    <form action="" method="get" class="mb-5">
        <div class = "form-row">
            <div class = "col-5">
                <input placeholder='検索キーワード' name="query" value="{{ request.GET.query }}" type="text" class ="form-control">
                <div class = "mt-2">
                    <button type="submit" class='submit btn btn-outline-primary'>検索する</button>
                    <a href="./" class='submit btn btn-outline-primary ml-2'>クリア</a>
                    <input type="checkbox" name="title" value="1" class = "ml-5">タイトル
                    <input type="checkbox" name="article" value="1" class = "ml-2">投稿内容
                </div>
            </div>
        </div>
    </form>

    <table class='table table-striped table-hover'>
        <tr>
            <th>投稿者</th>
            <th>内容</th>
        </tr>
        {% for article in object_list %}
        <tr>
            <td>
                <a href='{% url "bbs:detail" article.pk %}'>{{ article.title }} {{ article.author }}</a><br>
                作成日時：{{ article.created_at|date:"Y-m-j H:i" }}<br>
                更新日時：{{ article.updated_at|date:"Y-m-j H:i" }}
            </td>
            <td>{{ article.content|markdown|safe }}</td>
        </tr>
        {% endfor %}
    </table>

    {% if user.is_authenticated %}
    <p>
        <a href='{% url "bbs:create" %}'  class='btn btn-outline-primary'>新規投稿</a>
    </p>
    {% endif %}

{% endblock %}

my_project/myapp/bbs/templates/bbs/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset='utf-8'>
        <meta name='viewport' content='width=device-width, initial-scale=1, shrink-to-fit=no'>
        <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css'>
        <style>body {padding-top: 80px;}</style>
        <title>鳩でもわかるはじめてのDjango</title>
    </head>
    <body>
        <nav class='navbar navbar-expand-sm navbar-dark bg-dark fixed-top'>
            <a class='navbar-brand' href='{% url "bbs:index" %}'>BBS TOP</a>
        </nav>
        <div class='container'>
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>

my_project/myapp/templates/layout.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset='utf-8'>
        <meta name='viewport' content='width=device-width, initial-scale=1, shrink-to-fit=no'>
        <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css'>
        <style>
            body {padding-top: 80px;}
            h1 {font-size: 150%;}
            h2 {font-size: 130%;}
            h3 {font-size: 110%;}
            h4 {font-size: 100%;}
            h5 {font-size: 100%;}
            h6 {font-size: 100%;}
        </style>
        <title>鳩でもわかるはじめてのDjango</title>
    </head>
    <body>
        <nav class='navbar navbar-expand-sm navbar-dark bg-dark fixed-top'>
            <a class='navbar-brand' href='{% url "bbs:index" %}'>掲示板 TOP</a>
            <ul class='navbar-nav'>
                {% if user.is_authenticated %}
                    <!-- ログインしているとき -->
                    <li class='nav-time'>
                        <span class='navbar-text'>{{ user }} - </span>
                    </li>
                    <li class='nav-item'>
                        <a href='{% url "logout" %}' class='logout nav-link'>ログアウト</a>
                    </li>
                {% else %}
                    <!-- ログインしていないとき -->
                    <li class="nav-item">
                        <a href='{% url "login" %}' class='login nav-link'>ログイン</a>
                    </li>
                    <li class="nav-item">
                        <a href='{% url "accounts:signup" %}' class='signup nav-link'>ユーザー登録</a>
                    </li>
                {% endif %}
            </ul>
        </nav>
        <div class='container'>
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>